INSERT INTO TO_DO VALUES(1, 'Grocery List', 'Evening Grocery List or Wife will get mad', 'Arnold Amaya');
INSERT INTO ITEM VALUES(1, 'Milk', false, 1);
INSERT INTO ITEM VALUES(2, 'Cereal', false, 1);
INSERT INTO ITEM VALUES(3, 'Meat', false, 1);
INSERT INTO ITEM VALUES(4, 'Water', false, 1);
INSERT INTO ITEM VALUES(5, 'Soda', false, 1);
INSERT INTO TO_DO VALUES(2, 'Grocery List', 'Evening Grocery List or Wife will get mad', 'Vinicio Guevara');
INSERT INTO ITEM VALUES(6, 'Almonds', false, 2);
INSERT INTO ITEM VALUES(7, 'Soda', false, 2);
INSERT INTO ITEM VALUES(8, 'Rice', false, 2);
INSERT INTO ITEM VALUES(9, 'Water', false, 2);
INSERT INTO ITEM VALUES(10, 'Soda', false, 2);
INSERT INTO TO_DO VALUES(3, 'Grocery List', 'Evening Grocery List or Wife will get mad', 'Nicolas Jalil');
INSERT INTO ITEM VALUES(11, 'Milk', false, 3);
INSERT INTO ITEM VALUES(12, 'Cereal', false, 3);
INSERT INTO ITEM VALUES(13, 'Meat', false, 3);
INSERT INTO ITEM VALUES(14, 'Water', false, 3);
INSERT INTO ITEM VALUES(15, 'Soda', false, 3);
INSERT INTO TO_DO VALUES(4, 'Grocery List', 'Evening Grocery List or Wife will get mad', 'Evelio Duarte');
INSERT INTO ITEM VALUES(16, 'Milk', false, 4);
INSERT INTO ITEM VALUES(17, 'Cereal', false, 4);
INSERT INTO ITEM VALUES(18, 'Meat', false, 4);
INSERT INTO ITEM VALUES(19, 'Water', false, 4);
INSERT INTO ITEM VALUES(20, 'Soda', false, 4);
INSERT INTO TO_DO VALUES(5, 'Grocery List', 'Evening Grocery List or Wife will get mad', 'Roman de las Heras');
INSERT INTO ITEM VALUES(21, 'Milk', false, 5);
INSERT INTO ITEM VALUES(22, 'Cereal', false, 5);
INSERT INTO ITEM VALUES(23, 'Meat', false, 5);
INSERT INTO ITEM VALUES(24, 'Water', false, 5);
INSERT INTO ITEM VALUES(25, 'Soda', false, 5);