DROP TABLE IF EXISTS TO_DO;
CREATE TABLE TO_DO(
    ID int AUTO_INCREMENT,
    NAME NVARCHAR(255),
    DESCRIPTION NVARCHAR(255),
    OWNER NVARCHAR(255),
    PRIMARY KEY (ID)
);
DROP TABLE IF EXISTS ITEM;
CREATE TABLE ITEM(
    ITEM_ID int AUTO_INCREMENT,
    DESCRIPTION NVARCHAR(255),
    DONE BOOLEAN NOT NULL,
    TO_DO_ID int,
    PRIMARY KEY (ITEM_ID),
    FOREIGN KEY (TO_DO_ID) REFERENCES TO_DO(ID) ON DELETE CASCADE
);